### ISSUE TITLE
Make the tab rows and columns configurable

### ISSUE THREAD

**Issue by ZepsiZola** [RedCarlos26/WiderTab#1]
Thank you for making this mod btw. I've been looking for one just like this for ages. Can a new feature be added where I can configure amount of rows in each column? So that I could make it have 30 rows in each column or something like that.

**Comment by RedCarlos26** [comment]
I don;t see how I could do this at the moment. Thanks for the suggesiton tho, I will see what I can do!

**Comment by Moonyol** [comment]
You would need to create a config file, read from it when initialising, and then set the constant to the value that was read.
